### ISSUE TITLE
手机版面菜单按钮消失

### ISSUE THREAD

**Issue by h2y** [h2y/germ#10]
![9332c534340c4dbb](https://cloud.githubusercontent.com/assets/12909077/24921402/50aca862-1f1d-11e7-9ca6-b49835aee98f.jpg)

与浏览器有关。

错误原因已定位：function.php 中 is_mobile() 不能正确获取本来应该是手机的 UA。

**Comment by Lensual** [comment]
不存在的（滑稽），电脑访问后再启用的模拟，所以根本没有 `mobile-nav` ，自然也看不到菜单。
另外一个问题就是页面被客户端/服务端缓存了。。。

倒是有个错位问题，图标有点向上偏。

**Comment by h2y** [comment]
<https://github.com/h2y/germ/commit/4cb7bf1cdd09a64bf77ea7655d7cb928ac4d047b>

图标错位的问题已解决
