### ISSUE TITLE
长评论 回复按钮影响回复内容错位 

### ISSUE THREAD

**Issue by Lensual** [h2y/germ#3]
补充图片

![qq 20170301223943](https://cloud.githubusercontent.com/assets/11309551/23464459/0715abf8-fed0-11e6-8d45-92a8b6fdbf63.png)
![qq 20170301223947](https://cloud.githubusercontent.com/assets/11309551/23464460/0760ac5c-fed0-11e6-9e3e-231208b5312f.png)

Chrome 56.0.2924.87 Win10 1920x1080

**Comment by h2y** [comment]
你好，主题中就是这么设计的，如果不喜欢可以在设置页面中的额外 CSS 里面添加：
```
.comment-body {
    position: relative;
}
.comment-content .reply {
    float: none;
    bottom: inherit;
    position: absolute;
    right: 1rem;
    top: 1rem;
}
```

**Comment by Lensual** [comment]
确定是这么设计的么？
在你的站点也会出现这个问题，我们能否线下交流测试一下？

![qq 20170301225233](https://cloud.githubusercontent.com/assets/11309551/23465134/43a8a8b6-fed2-11e6-897e-700586040633.png)
![qq 20170301225244](https://cloud.githubusercontent.com/assets/11309551/23465132/423cc818-fed2-11e6-8f1b-3e3f4f26e736.png)

**Comment by Lensual** [comment]
我的解决方案
```
.comment-content > .comment-metadata {
    margin-bottom: 4px;
}
```

**Comment by h2y** [comment]
是的，我的原意就是这样的。
这样可以避免 ‘显示’ 按钮把评论文字给遮盖住了。
