### ISSUE TITLE
标签云特殊页面无法展现

### ISSUE THREAD

**Issue by h2y** [h2y/germ#5]
<https://hzy.pw/germ-tagspage>

在我的服务器上出现了这样的问题，但在其他环境下表现正常。

**Comment by Lensual** [comment]
502 Bad Gateway

2017/03/10 06:58:50 [notice] 9089#0: *417977 "/wp-admin$" does not match "/标签云", client: 163.44.xxx.xxx, server: lensual.space, request: "GET /%e6%a0%87%e7%ad%be%e4%ba%91 HTTP/2.0", host: "lensual.space", referrer: "https://lensual.space/wp-admin/post.php?post=494&action=edit"

看样子像是urlRewrite问题，不过我确定urlRewrite规则没有问题。其他页面正常。排除中文URL问题。

环境Debian+Nginx+php7

**Comment by vpsceo** [comment]
1、网站云图的确用不来，是我没找到开关还是咋的

2、myQaptcha，防垃圾插件拖不动，感觉是插件和模板冲突了，拖不动！

**Comment by h2y** [comment]
@vpsceo 你的问题与本 issue 无关，新建个 issue 更好。

> 1、网站云图的确用不来，是我没找到开关还是咋的

我网站中的网站云图使用的是插件：WP Category Tag Cloud

> 2、myQaptcha，防垃圾插件拖不动，感觉是插件和模板冲突了，拖不动！

未测试与此插件的兼容，你可以看看浏览器控制台是否有报错。

**Comment by vpsceo** [comment]
主题里的鼠标在哪里关闭那个特效

**Comment by h2y** [comment]
fixed
